### ISSUE TITLE
Typo in requirements.txt

### ISSUE THREAD

**Issue by notsniped** [thatOneArchUser/discord-py-generator#4]
![Screenshot_20220301_113521](https://user-images.githubusercontent.com/72265661/156114272-178eb29a-4add-47d4-8b8a-452430a0f3cf.png)

I think it should be **Flask**??

```
discord==1.7.3
requests==2.26.0
Flask==2.0.2
praw==7.5.0
prawcore==2.3.0
```

And this would be the untypoed version

**Comment by thatOneArchUser** [comment]
thx didnt notice it

**Comment by notsniped** [comment]
np
